### ISSUE TITLE
Document haddocks and include README in package

### ISSUE THREAD

**Issue by sjakobi** [athanclark/urlpath#9]
I tried to make sense of the haddocks for urlpath for quite a while before I looked at the repo to find the README…

Both hackage and stackage now show the README on the package page if it is included in the package, so it would be good to do that.

**Comment by athanclark** [comment]
Hackage builds this independently IIRC, I don't know how to do it manually :\

**Comment by sjakobi** [comment]
I believe it's enough to list the README in the `extra-source-files`, in this case:

```
Extra-Source-Files: README.md
```
